# Generated by Django 3.1 on 2021-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210117_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='friday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='internet',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='monday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='notmidman',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='ref1email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='ref2email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='saturday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='skillset',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='sunday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='terms',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='thursday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='tuesday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='wednesday',
            field=models.BooleanField(),
        ),
    ]
