# Generated by Django 3.1.3 on 2021-01-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210114_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='internet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='notmidman',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='skillset',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='yearexp',
            field=models.CharField(max_length=50),
        ),
    ]
