# Generated by Django 3.1.3 on 2021-01-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210118_0956'),
        ('backend', '0003_auto_20210119_1643'),
    ]

    operations = [
    ]
