# Generated by Django 3.1.3 on 2021-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_merge_20210125_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='friday',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='internet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='monday',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='notmidman',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='saturday',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='skillset',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='sunday',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='terms',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='thursday',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='tuesday',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='wednesday',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
