# Generated by Django 3.1.3 on 2021-01-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210125_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='category',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
