export const ADD_SERVICEPROVIDER = "ADD_SERVICEPROVIDER";
export const GET_SERVICEPROVIDERS = "GET_SERVICEPROVIDERS";
export const GET_ONE_SERVICEPROVIDER = "GET_ONE_SERVICEPROVIDER";
export const UPDATE_SERVICEPROVIDER = "UPDATE_SERVICEPROVIDER"
export const DELETE_SERVICEPROVIDER = "DELETE_SERVICEPROVIDER";

export const ADD_BOOKING = "ADD_BOOKING";
export const GET_BOOKINGS = "GET_BOOKINGS";
export const GET_ONE_BOOKING = "GET_ONE_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING"
export const DELETE_BOOKING = "DELETE_BOOKING";


export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";



export const ADD_RATING= "ADD_RATING";
export const GET_RATINGS = "GET_RATINGS";
export const GET_ONE_RATING = "GET_ONE_RATING";
export const UPDATE_RATING = "UPDATE_RATING"
export const DELETE_RATING = "DELETE_RATING";