export const ADD_SERVICEPROVIDER = "ADD_SERVICEPROVIDER";
export const GET_SERVICEPROVIDERS = "GET_SERVICEPROVIDERS";
export const GET_ONE_SERVICEPROVIDER = "GET_ONE_SERVICEPROVIDER";
export const UPDATE_SERVICEPROVIDER = "UPDATE_SERVICEPROVIDER"
export const DELETE_SERVICEPROVIDER = "DELETE_SERVICEPROVIDER";

export const ADD_BOOKING = "ADD_BOOKING";
export const GET_BOOKINGS = "GET_BOOKINGS";
export const GET_ONE_BOOKING = "GET_ONE_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING"
export const DELETE_BOOKING = "DELETE_BOOKING";


